language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - clang-3.6
      - autoconf-archive
      - valgrind

env:
  - CFLAGS="-g"

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sh autogen.sh

before_script:
  - sudo add-apt-repository ppa:adiscon/v8-stable -y
  - sudo apt-get update -qq
  - sudo apt-get -qq --force-yes install valgrind libfastjson
  - # note: valgrind is only available on Linux
  - if [ "$CC" == "gcc" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export ENA_VG="--enable-valgrind"; fi
  - if [ "$CC" == "clang" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export SANITIZER="-fsanitize=address" ; fi
  - if [ "$CC" == "clang" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CFLAGS="$CFLAGS -fsanitize=address" ; fi
  - ./CI/check_codestyle.sh
  - ./configure --enable-performance-testbench $ENA_VG

script:
  - if [ "$CC" == "clang" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then  scan-build-3.6 --status-bugs make check TESTS="" && make clean ; fi
  - make
  - valgrind --tool=callgrind ls
  - export VERBOSE=1
  - make check
  - cat tests/test-suite.log
  - cat tests/perf_to_string.trs
  - make distcheck
